### ISSUE TITLE
[Feature request] Customizable "locust_exporter" Image 

### ISSUE THREAD

**Issue by molixianggu** [AbdelrhmanHamouda/locust-k8s-operator#116]
**Is your feature request related to a problem? Please describe.**
I often encounter timeouts and instability while pulling the locust_exporter image due to network issues. This creates a frustrating experience.

**Describe the solution you'd like**
I would like to have the ability to customize the locust_exporter image in the locust-k8s-operator. This customization feature would allow me to configure the image repository URL and tag, enabling me to choose a mirror or address that suits my network environment and preferences. 

Not only does this modification address network-related issues, but it also makes it possible for users to further customize the exported monitoring metrics.

**Comment by AbdelrhmanHamouda** [comment]
Hello @molixianggu, 
Thank you for taking the time to open this issue. I understand the reasoning behind this GH-issue and generally support it. If I may, other than the network issue, can I ask if you already have a better/different metric exporter in mind that you would like to use?

**Comment by molixianggu** [comment]
Thank you for your prompt response and understanding regarding the issue I raised. I appreciate your support for my feature request.
> can I ask if you already have a better/different metric exporter in mind that you would like to use?

I apologize for the confusion, I don't have a specific metric exporter in mind that. However, my plan is to enhance the monitoring capabilities based on specific business requirements by incorporating additional statistical information and labels.

**Comment by AbdelrhmanHamouda** [comment]
Hello @molixianggu, 
I see. Thank you for your patience with me regarding this. I generally as stated before, agree with this and don't see a reason why not to update the operator so it can take a configurable metric exporter image. 

However, and to be honest with you, this item won't be on top of my priority list at the moment as i'm covering other features and plan to introduce them which is consuming the time I'm able to dedicate to the project. 

That being said, I fully welcome contributions to the project "we already have several" as I believe they are a strong element to the health of the operator.

**Comment by AbdelrhmanHamouda** [comment]
Hello @molixianggu, 
any thoughts on my previous comment? 

In order to declutter the project board, I'm moving to remove inactive issues, however, I want to make sure first that the need is no longer there or that it is not a priority for you anymore.

**Comment by molixianggu** [comment]
I must admit that I'm not very familiar with Java, but I managed to get the project working by making some simple string modifications and recompiling it. As of now, everything is running smoothly, and I appreciate your support.

Given the current state, I agree with closing this issue.
