### ISSUE TITLE
Ability to add labels to created resources[Feature request]

### ISSUE THREAD

**Issue by PaulRudin** [AbdelrhmanHamouda/locust-k8s-operator#151]
**Is your feature request related to a problem? Please describe.**
I'm trying to set up a serviceMonitor to for prometheus to scrape the services created by the operator, but the servicemonitor selector needs labels on the target services

**Describe the solution you'd like**
Add key(s) to the values.yaml to allow labels to be attached to the resources created by the operator

**Comment by AbdelrhmanHamouda** [comment]
Hello @PaulRudin, 
Thank you for taking the time to open this feature request. 

If I'm understanding your request properly, you are basically looking for way to inject specific labels and annotations to the generated pods so your  servicemonitor can detect them during service discovery. If that is the case, it is already possible to do this "add annotations and labels" by adding them to the deployed CR. [Here are the docs for that.](https://abdelrhmanhamouda.github.io/locust-k8s-operator/getting_started/?h=labels#labels-and-annotations). 

Additionally,  if you don't have a hard requirement on **specific** label / annotation to be used, the Operator already provide a number of consistent tags on all generated resources. This includes: 
- `managed-by`
-  `performance-test-name`
- `performance-test-pod-name`
  - the master pod will always have `-master` at the end  

Hope this answers your question and meets your need. I will close the issue but in case the answer is not satisfactory, please feel free and encouraged to reopen it again.
