### ISSUE TITLE
Test results logged by locust master are truncated

### ISSUE THREAD

**Issue by SkylerLutz** [AbdelrhmanHamouda/locust-k8s-operator#190]
**Describe the bug**
If there are a high number of endpoints under test, the report that is logged by master is truncated. I cannot see the # reqs, fails, avg,min,max,med, etc of my endpoints. I can only see the bottom half of the "Response time percentiles (approximated)" part of the report. This is problematic because I don't know how else to view the results other than looking at the locust masters' logs. I don't want to bucket the endpoints into coarser-grained buckets because then I will lose relationship info between endpoint and min/max/avg/etc. 

Is there a better way to view the full (un-truncated) report? Is it exported to a file or something? I don't have the bandwidth to integrate with metrics/grafana/whatever. Thanks

**Comment by dennrich** [comment]
I'm also interested in downloading the report as a file. We also have the prometheus-stack running so instructions on how to set this up using metrics is also welcome on my side.

**Comment by AbdelrhmanHamouda** [comment]
Hello @SkylerLutz , 

Thank you for taking the time to share this feedback, can i kindly ask you to share a screenshot or something similar of what you experience. We regularly runs huge tests with literal millions of simulated users over +100 worker pods in the same test and never ran into this problem. 

As i mentioned, a screenshot or something of similar nature would be awesome. Also some info on how the test is launched (maybe the used CR)? 

 Meanwhile, I see the demand for releasing a guide on how to connect the metrics which i'll work on (tracked in a different issue)

**Comment by AbdelrhmanHamouda** [comment]
Hello @dennrich, 
> I'm also interested in downloading the report as a file. 
This is both very easy and very hard. Can i kindly ask you to open another issue for it so i can discuss with you and not over take this one?

**Comment by dennrich** [comment]
@AbdelrhmanHamouda Thanks, I created #195
