### ISSUE TITLE
[Feature request] Download HTML report

### ISSUE THREAD

**Issue by dennrich** [AbdelrhmanHamouda/locust-k8s-operator#195]
**Is your feature request related to a problem? Please describe.**
Our QA team would like to download an HTML report after the test was finished. When the `LocustTest` job is done the master and worker pods are stopped, which prevents from downloading an HTML report generated with the `--html` option.

**Describe the solution you'd like**
A simple approach might look like this: Add an option to the operator to create an `emptyDir` volume and a master sidecar container that mounts this volume to a specific directory. Keep the sidecar running after the test is finished to make it possible to download the file using `kubectl`.

**Describe alternatives you've considered**
Alternatives:
- Storage backend support like S3 to save the report there
- An operator option to create/mount a PVC and save the report there. The PVC can then be mounted to a temporary pod to download the file.

**Comment by AbdelrhmanHamouda** [comment]
@dennrich , is this request, still interesting to you?

**Comment by dennrich** [comment]
No, we moved to a custom solution to run our locust tests

**Comment by AbdelrhmanHamouda** [comment]
hmm, this is a bit unfortunate! 
was the ability to download the reports the factor to not use the operator @dennrich ?

**Comment by dennrich** [comment]
@AbdelrhmanHamouda We also faced some permission issues on AWS EKS when trying to create the test resources we were not able to solve quickly. As I had to deliver a working solution I developed something based on manually created jobs and configmaps.

**Comment by AbdelrhmanHamouda** [comment]
i see, if at any point you want to revisit this, let me know and i can provide you with assistance on this front. 

we use the operator in my organisation in AWS EKS on a lot of regions and vpcs running thousands of tests with full observability to Datadog through metrics (and Newrelic before that).

@dennrich
