### ISSUE TITLE
[Feature request] Add a TTL period to deployed jobs

### ISSUE THREAD

**Issue by jachinte** [AbdelrhmanHamouda/locust-k8s-operator#52]
**Is your feature request related to a problem? Please describe.**
When a test ends, `LocustTest` resources have to be manually deleted.

**Describe the solution you'd like**
I'd like to set the [time-to-live after finished](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) attribute in the Job spec, so that master and worker jobs delete themselves when a test ends. This would be optional.

**Describe alternatives you've considered**
Call method `withTtlSecondsAfterFinished(X)` when creating job specs in class `ResourceCreationHelpers`. Parameter `X` would be defined in Helm's `values.yaml` and passed to the operator as an environment variable.

**Additional context**
I'm willing to implement this change if you think they'd be a good addition to the repository.

**Comment by AbdelrhmanHamouda** [comment]
Hello, 
I think the idea is good and has valid uses cases. As you mentioned in the additional context about your willingness to do a PR, Your contribution would be completely welcomed. 

For the documentation, I am planning to add a HELM breakdown page in the docs. I was pushing it back a bit till i finish other features but given this issue, I would say this is now more pressing to get out. As such, when you are opening the PR, please take a look at the main branch in case that docs page is added so you can add your contribution to it or ping me here to check on its status.
