### ISSUE TITLE
[Feature request] deploy load test script other than operator namespace

### ISSUE THREAD

**Issue by prasanna12510** [AbdelrhmanHamouda/locust-k8s-operator#82]
**Is your feature request related to a problem?**
allows flexibility to specify custom namespace other than operator namespace
**Describe the solution you'd like**
adding the serviceaccount and role that will be created in custom namespace

**Comment by prasanna12510** [comment]
support helmchart to create load test script other than operator namespace

<img width="1454" alt="Screenshot 2023-01-25 at 2 02 04 PM" src="https://user-images.githubusercontent.com/11510186/214515580-d98b6ab2-835e-4f68-a34e-eb1316c840a9.png">

**Comment by AbdelrhmanHamouda** [comment]
Hello @prasanna12510, 
Thank you for taking the tine to go through the project and voicing your thoughts as well. It is a valid point you are bringing and I see no reason to not have it.  
would you be willing to contribute a PR for this? if no, it may take me a minute to get to it as i have some points already in the backlog. 

The implementation would need to be controllable with HELM value, if set to `true` then permission to all namespaces are deployed.  also a small peace of documentation to explain what the feature do.

**Comment by prasanna12510** [comment]
sure I can contribute to helmchart to add the namespaceoption to set customizable accordingly set rbac resource

**Comment by AbdelrhmanHamouda** [comment]
hello @prasanna12510, are you working on this?
