### ISSUE TITLE
[Feature request] how to download locust report after test execution

### ISSUE THREAD

**Issue by prasanna12510** [AbdelrhmanHamouda/locust-k8s-operator#86]
**Is your feature request related to a problem? Please describe.**
Download detailed report after test execution

**Describe the solution you'd like**
Integrate slack notification with download report option

**Additional context**
Its very difficult to keep in track while executing the test

**Comment by AbdelrhmanHamouda** [comment]
Hello @prasanna12510, 
Could you provide an example of the behaviour you are expecting? 
I get the gist of your request  but a more detailed use case is needed.

**Comment by prasanna12510** [comment]
how does the user know if the test has been completed as the operator cannot send any notification to download the report or has an integration with an external storage bucket to upload the report after completion

**Comment by prasanna12510** [comment]
@AbdelrhmanHamouda if we have provision to add external secret to crd we can utilise the https://github.com/locustio/locust/blob/master/examples/test_data_management.py#L48 As there is a listener event which tells for shutdown of locust.  if we utilise this function then we can send the test report to gcs bucket ? and can also integrate with slack. whats your view on this ^

**Comment by AbdelrhmanHamouda** [comment]
So if i understand you correctly, the actual request is to extend the CRD and the controller to be able to mont secretes to pods which then you can independently read and utilise in your `quitting` event. 

Is that an accurate understanding of your request?
