### ISSUE TITLE
How to set the custom parameters for the locust loadtest

### ISSUE THREAD

**Issue by prasanna12510** [AbdelrhmanHamouda/locust-k8s-operator#88]

**Comment by AbdelrhmanHamouda** [comment]
Hello @prasanna12510, 
can you add more context to your question?

**Comment by prasanna12510** [comment]
we can add the arguments to locust test script and use the same via masterseedcommand 

https://github.com/locustio/locust/blob/master/examples/add_command_line_argument.py
