### ISSUE TITLE
[Feature request] add imagePullSecrets to pull the customImage from Private Registry

### ISSUE THREAD

**Issue by prasanna12510** [AbdelrhmanHamouda/locust-k8s-operator#89]
**Is your feature request related to a problem? Please describe.**
add support for imagePullSecrets to pull the customImage from Private Registry

**Describe the solution you'd like**
add imagePullSecrets with Image and ImagePullPolicy Similar to deployments

**Comment by AbdelrhmanHamouda** [comment]
Hello @prasanna12510 , 

Thank you for taking the time to report this enhancement. This is a nice addition to make the operator more feature complete. That being said, atm, this won't make it to the top of my priority list. However, I strongly invite you to open a PR with this contribution and i can review it and work together on it till it is added to the project. 

I am assuming that you are looking for something similar to this: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by jachinte** [comment]
@AbdelrhmanHamouda I could help with this.

Just to be sure, you're talking about the `LoadTest` resource, right? Another possibility would be adding this to the operator itself - @prasanna12510

**Comment by AbdelrhmanHamouda** [comment]
solved with https://github.com/AbdelrhmanHamouda/locust-k8s-operator/pull/98
