### ISSUE TITLE
[Feature request] added cpu and memory resources to master and workers

### ISSUE THREAD

**Issue by prasanna12510** [AbdelrhmanHamouda/locust-k8s-operator#90]
**Is your feature request related to a problem? Please describe.**
add CPU request and limit for master and workers

**Describe the solution you'd like**
add the requests and limits for CPU and memory in container specs

**Comment by AbdelrhmanHamouda** [comment]
Hello, 
@prasanna12510, this is already supported by the setting the following [values](https://github.com/AbdelrhmanHamouda/locust-k8s-operator/blob/master/charts/locust-k8s-operator/values.yaml#L70-L77) in the Operator's HELM chart.

**Comment by ishan-12** [comment]
Hello @AbdelrhmanHamouda, can you please provide an example of how to do so? For eg, I updated the values.yaml and then installed it using `helm install locust-operator locust-k8s-operator/locust-k8s-operator -f values.yaml` but I still see "exceeded CPU threshold (will only log this once per worker)". I am trying to run locust in the headless state so I pass those parameters in masterCommandSeed which seems to be fine just that I keep running into CPU errors. The maximum number of requests I am seeing with m5.4xlarge (20 workers and 100 users) is 247 req/s.

**Comment by AbdelrhmanHamouda** [comment]
hello @ishan-12 ,
can you kindly share your values.yaml used? 
In my case for example I am using terraform to deploy the operator through the HELM provider and overwriting those values and it has been working perfectly.
